Cleanup all code
agrirobo/arcsys2 pull request #34
Opened 2016-11-27 07:23 UTC by forno

とりあえず不必要なファイルを削除削除。
あと不必要な依存も削除削除。
あとさっきのPull-requestでなにげにcontrolをぶっ壊されていたのでFix。

2016-11-27 11:05 UTC, YamaCIR-KIT commented
`src/arcsys2_description/package.xml`で dependにxacroを追加している意味なくね？
それ以外は特に言うことありません

2016-11-27 11:06 UTC, yamacir-kit requested changes
`src/arcsys2_description/package.xml`で dependにxacroを追加している意味なくね？
それ以外は特に言うことありません

2016-11-27 11:25 UTC, forno commented
実行時にxacroパッケージを呼んでいます。 exec_dependでもいいですが、いちおうこのパッケージ作るのに使ったのでdependにしておこうかといったところです。

2016-11-28 03:54 UTC, yamacir-kit approved these changes

2016-11-28 03:55 UTC, YamaCIR-KIT commented
xacroとgazeboがごちゃまぜになってた
俺がどうかしてたわ

2016-11-28 03:55 UTC, merged